name: jehegram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0-65.0.dev <4.0.0'

isar_version: &isar_version 3.1.0 # define the version to be used

dependencies:
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.2
  get: 4.6.55
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  isar_generator: *isar_version
  build_runner: any

flutter: 
  uses-material-design: true

